[[redirects]]
  from = "/index.htm"
  to = "/de/index.htm"

[[redirects]]
  from = "/"
  to = "/de/"

[[redirects]]
  from = "/index.htm/"
  to = "/de/index.htm/"

[[redirects]]
  from = ""
  to = "/de/"

[[redirects]]
  from = ""
  to = "/de/index.htm"

[[redirects]]
  from = "https://type-error.netlify.app/"
  to = "https://type-error.netlify.app/de/index.htm"
  
[[redirects]]
  from = "https://type-error.netlify.app/"
  to = "https://type-error.netlify.app/de/"