[[redirects]]
  from = "/"
  to = "/de/"

[[redirects]]
  from = "/index"
  to = "/de/"

[[redirects]]
  from = "/index.htm"
  to = "/de/"

[[redirects]]
  from = "/index.html"
  to = "/de/"

[[redirects]]
  from = "/start"
  to = "/de/"

[[redirects]]
  from = "/home"
  to = "/de/"

[[redirects]]
  from = "/TypeError"
  to = "/de/"

[[redirects]]
  from = "/type-error"
  to = "/de/"

[[redirects]]
  from = "/"
  to = "/en/"
  conditions = {Language = ["en"]}
