[[redirects]]
  from = "/*"
  to = "/en/"
  status = 301
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/*"
  to = "/de/"

[[redirects]]
  from = "/en/404.html"
  to = "/en/page-not-found.htm"
  status = 404
  force = true
  conditions = {Language = ["en"]}

  [[redirects]]
  from = "/de/404.html"
  to = "/de/page-not-found.htm"
  status = 404