[[headers]]
  for ="*"
    [headers.values]
      # Content-Security-Policy = "default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; img-src 'self'; media-src 'self'; object-src 'none'; script-src 'self'; style-src 'self' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='; font-src 'self'"
      Content-Security-Policy = "base-uri 'none'; form-action 'none'; frame-ancestors 'none'; img-src d2j6dbq0eux0bg.cloudfront.net 'self' 'unsafe-eval'; media-src 'self'; object-src 'none'; font-src 'self' don16obqbay2c.cloudfront.net ec-icons.shopsettings.com"
      Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=()"
      Referrer-Policy = "same-origin"
      Strict-Transport-Security = "max-age=31536000; includeSubdomains; preload"
      
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      X-Permitted-Cross-Domain-Policies = "none"



# Language redirect
[[redirects]]
  from = "/"
  to = "/de/"
  status = 301
  force = true
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/"
  to = "/de/"
  status = 301
  force = true
  conditions = {Country = ["de"]}

 [[redirects]]
  from = "/"
  to = "/en/"
  status = 301
  force = true



# 404 redirection
[[redirects]]
  from = "/de/*"
  to = "/de/page-not-found.htm"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/page-not-found.htm"
  status = 404  

[[redirects]]
  from = "/*"
  to = "/404.htm"
  status = 404
