[[redirects]]
  from = "/en/*"
  to = "/en/page-not-found.htm"
  status = 404

  [[redirects]]
  from = "/de/*"
  to = "/de/page-not-found.htm"
  status = 404

[[redirects]]
  from = "/*"
  to = "/en/"
  status = 301
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/*"
  to = "/de/"